### ISSUE TITLE
Kubectl -f [Filename] does not create anything

### ISSUE THREAD

**Issue by ramonrue** [coreos/coreos-kubernetes#219]
I have set up a kubernetes cluster on coreos with the official documentation. 

```shell
core@hostname ~ $ kubectl get nodes
NAME           LABELS                                STATUS    AGE
192.168.1.32   kubernetes.io/hostname=192.168.1.32   Ready     3h
192.168.1.33   kubernetes.io/hostname=192.168.1.33   Ready     3h
core@hostname ~ $ kubectl get ep
NAME         ENDPOINTS          AGE
kubernetes   192.168.1.31:443   4h
```
The cluster seems to be working. 
Now I wanted to set up the web interface with the following yaml:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-ui
  namespace: kube-system
  labels:
    k8s-app: kube-ui
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeUI"
spec:
  selector:
    k8s-app: kube-ui
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-ui-v4
  namespace: kube-system
  labels:
    k8s-app: kube-ui
    version: v4
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-ui
    version: v4
  template:
    metadata:
      labels:
        k8s-app: kube-ui
        version: v4
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kube-ui
        image: gcr.io/google_containers/kube-ui:v4
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
```

Now when I want to create / start the interface, I enter the following command:
```shell
core@hostname ~ $ kubectl create  -f kube-ui.yaml --namespace=kube-system
service "kube-ui" created
replicationcontroller "kube-ui-v4" created
```
The service & rc seem to be created. My Problem:
The following command:
```shell
core@hostname ~ $ kubectl get pods
NAME      READY     STATUS    RESTARTS   AGE
core@hostname ~ $ 
```

Also I cannot access the webinterface. After adding the necessary client certificates, I try to access the link "https://192.168.1.31/ui" which redirects me to "https://192.168.1.31/api/v1/proxy/namespaces/kube-system/services/kube-ui/#/dashboard/". There I receive the following text:
```plain
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "endpoints \"kube-ui\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kube-ui",
    "kind": "endpoints"
  },
  "code": 404
}
```

------------------------------------
I also tried the dns-addon in the documentation, but I do not see that with a "kubectl get pods" too...
