### ISSUE TITLE
Cannot run apiserver with TLS enabled

### ISSUE THREAD

**Issue by aknuds1** [coreos/coreos-kubernetes#295]
Using CoreOS alpha (970.1.0), I've followed the CoreOS [guide for setting up Kubernetes](https://coreos.com/kubernetes/docs/latest/getting-started.html), but have diverged from it in order to enable TLS, with the indispensable help of @rapenchukd. So far, I've got a single-node TLS secured etcd cluster and flanneld up and running. Where I'm at right now is that the apiserver pod won't launch, seemingly because the certificate file can't be found: 
```
sudo cat /var/log/containers/kube-apiserver-*
{"log":"I0227 22:36:06.389956       1 plugins.go:71] No cloud provider specified.\n","stream":"stderr","time":"2016-02-27T22:36:06.39033845Z"}
{"log":"F0227 22:36:06.390088       1 server.go:416] Failure to start kubelet client: open /etc/ssl/etcd/master1-master-client.pem: no such file or directory\n","stream":"stderr","time":"2016-02-27T22:36:06.390393556Z"}
```

Note that I had to find out by myself how to at all find the reason for the pod launch failure, as it wasn't stated in the journal at all (just that it wouldn't launch).

I do know that the certificate file should be accessible though, as I've tried running the corresponding docker command manually and it works: `docker run -p 443:443 -v /etc/kubernetes:/etc/kubernetes:ro -v /etc/ssl/etcd:/etc/ssl/etcd:ro gcr.io/google_containers/hyperkube:v1.1.2 /hyperkube apiserver --bind-address=0.0.0.0 --insecure-bind-address=127.0.0.1 --etcd-config=/etc/kubernetes/etcd.client.conf --allow-privileged=true --service-cluster-ip-range=10.3.0.0/24 --secure-port=443 --advertise-address=172.31.29.111 --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota --kubelet-certificate-authority=/etc/ssl/etcd/ca.pem --kubelet-client-certificate=/etc/ssl/etcd/master1-master-client.pem --kubelet-client-key=/etc/ssl/etcd/master1-master-client-key.pem --client-ca-file=/etc/ssl/etcd/ca.pem --tls-cert-file=/etc/ssl/etcd/master1-master-client.pem --tls-private-key-file=/etc/ssl/etcd/master1-master-client-key.pem`

My (failing) apiserver pod spec looks like this:
```
apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: gcr.io/google_containers/hyperkube:v1.1.2
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --insecure-bind-address=127.0.0.1
    - --etcd-config=/etc/kubernetes/etcd.client.conf
    - --allow-privileged=true
    - --service-cluster-ip-range=10.3.0.0/24
    - --secure-port=443
    - --advertise-address=172.31.29.111
    - --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
    - --tls-cert-file=/etc/ssl/etcd/master1-master-client.pem
    - --tls-private-key-file=/etc/ssl/etcd/master1-master-client-key.pem
    - --client-ca-file=/etc/ssl/etcd/ca.pem
    - --kubelet-certificate-authority=/etc/ssl/etcd/ca.pem
    - --kubelet-client-certificate=/etc/ssl/etcd/master1-master-client.pem
    - --kubelet-client-key=/etc/ssl/etcd/master1-master-client-key.pem
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/ssl/etcd
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/kubernetes
      name: conf-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
    path: /etc/ssl/etcd
    name: ssl-certs-kubernetes
  - hostPath:
    path: /etc/kubernetes
    name: conf-kubernetes
  - hostPath:
    path: /usr/share/ca-certificates
    name: ssl-certs-host
```
