### ISSUE TITLE
externalDNSName is not validated against hostedZone

### ISSUE THREAD

**Issue by colhom** [coreos/coreos-kubernetes#401]
```yaml
createRecordSet: true
hostedZone: staging.core-os.net
externalDNSName: my-cluster.staging2.core-os.net
```

`kube-aws render` will still succeed, even though we know that this cluster config is invalid because `externalDNSName` is not a subdomain of `hostedZone`.

@cgag can you add:
* a validation check in `Config.valid()`, which checks that `externalDNSName` is a valid sub-domain of `hostedZone`?
* tests in `config_test.go` which test valid and invalid relationship between the two fields?
