### ISSUE TITLE
Error pulling private images

### ISSUE THREAD

**Issue by arkkanoid** [coreos/coreos-kubernetes#498]
Hi,
I've configured all coreos nodes with my credentials in the dockercfg file. I've applied this configuration in core and root user as is specified in: 
http://kubernetes.io/docs/user-guide/images/#configuring-nodes-to-authenticate-to-a-private-repository

If I try to pull a private image with any of this users it works fine. 

But when I want to create a new pod from a private image I get an error:

    Failed to pull image "XXX/xxxxxx:0.1": Error: image XXX/xxxxxx not found

Is there a problem pulling private images from kubernetes?

**Comment by robszumski** [comment]
Kubernetes adds some special magic to dynamically add credentials when pulling images through its APIs (ie. when you create a pod) and the source for those is a special type of secret, called a PullSecret.

The way this works in practice is you [first create your PullSecret](http://kubernetes.io/docs/user-guide/images/#creating-a-secret-with-a-docker-config) with your creds in it, like this:

```
$ kubectl create secret docker-registry myregistrykey --docker-server=DOCKER_REGISTRY_SERVER --docker-username=DOCKER_USER --docker-password=DOCKER_PASSWORD --docker-email=DOCKER_EMAIL
secret "myregistrykey" created.
```

And then tell Kubernetes to use that PullSecret when creating your pod with the `imagePullSecrets:` parameter:

```
apiVersion: v1
kind: Pod
metadata:
  name: foo
  namespace: awesomeapps
spec:
  containers:
    - name: foo
      image: janedoe/awesomeapp:v1
  imagePullSecrets:
    - name: myregistrykey
```
