### ISSUE TITLE
kube-aws up fails using multiple AZ/Subnets

### ISSUE THREAD

**Issue by harsha-y** [coreos/coreos-kubernetes#510]
kube-aws validate succeeds without any errors. kube-aws up fails.

kube-aws version -
```
kube-aws version f74499b08fb2a10e7085602cc6ebf4f854a3a7c9
```

Error -
```
SHELL$ kube-aws up
Creating AWS resources. This should take around 5 minutes.
Error: Error creating cluster: error validating existing VPC: error parsing instances cidr  : invalid CIDR address:
```

Configuration -
```
# ID of existing VPC to create subnet in. Leave blank to create a new VPC
vpcId: vpc-xxxxxxxx

# ID of existing route table in existing VPC to attach subnet to. Leave blank to use the VPC's main route table.
# routeTableId: rtb-xxxxxxxx

# CIDR for Kubernetes VPC. If vpcId is specified, must match the CIDR of existing vpc.
vpcCIDR: "172.32.0.0/16"

# CIDR for Kubernetes subnet when placing nodes in a single availability zone (not highly-available) Leave commented out for multi availability zone setting and use the below `subnets` section instead.
# instanceCIDR: "172.32.1.0/24"

# Kubernetes subnets with their CIDRs and availability zones. Differentiating availability zone for 2 or more subnets result in high-availability (failures of a single availability zone won't result in immediate downtimes)
subnets:
  - availabilityZone: us-east-1a
    instanceCIDR: "172.32.1.0/24"
  - availabilityZone: us-east-1b
    instanceCIDR: "172.32.3.0/24"
  - availabilityZone: us-east-1c
    instanceCIDR: "172.32.5.0/24"

# IP Address for the controller in Kubernetes subnet. When we have 2 or more subnets, the controller is placed in the first subnet and controllerIP must be included in the instanceCIDR of the first subnet. This convention will change once we have H/A controllers
controllerIP: 172.32.1.100
```
