### ISSUE TITLE
AWS EBS timeout using kube-aws

### ISSUE THREAD

**Issue by samhagan** [coreos/coreos-kubernetes#582]
I'm setting up a kubernetes cluster to run jenkins on AWS.  Using kube-aws to generate the cluster, I can't get EBS to mount (although it shows in-use after creating the deployment).  I've made sure the EBS is available (always new) and in the same availability zone.  The same deployment works when using kube-up from kubernetes.io.  Below are the details.

I've tried hyperkube 1.3.0 and 1.3.2.

Deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: master
        image: jenkins:2.7.1-alpine
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
      volumes:
      - name: jenkins-home
        awsElasticBlockStore:
          volumeID: vol-9xxxxx
          fsType: ext4
```

Error message:

```
FirstSeen	LastSeen	Count	From							SubobjectPath	Type	Reason		Message
  ---------	--------	-----	----							-------------	--------	------	 	-------
  14m		14m		1	{default-scheduler }							NormalScheduled	Successfully assigned jenkins-1059742402-b96n5 to ip-10-0-0-50.us-west-2.compute.internal
  12m		1m		6	{kubelet ip-10-0-0-50.us-west-2.compute.internal}			Warning		FailedMount	Unable to mount volumes for pod "jenkins-1059742402-b96n5_jenkins(76e01b91-4eb9-11e6-9fb1-0a937718ab49)": timeout expired waiting for volumes to attach/mount for pod "jenkins-1059742402-b96n5"/"jenkins". list of unattached/unmounted volumes=[jenkins-home]
  12m		1m		6	{kubelet ip-10-0-0-50.us-west-2.compute.internal}			Warning		FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "jenkins-1059742402-b96n5"/"jenkins". list of unattached/unmounted volumes=[jenkins-home]
```

**Comment by doubliez** [comment]
Same problem for me, I just deployed a new Kubernetes cluster with kube-aws (compiled from current master) and my EBS volume fails to mount with the same timeout error.

For me the volume even remains in the "available" state on AWS.

Tried with both hyperkube 1.3.0 and 1.3.2 as well.

Here is my replication controller:

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: grafana/grafana
          name: grafana
          ports:
            - containerPort: 3000
              name: grafana
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: staging-grafana-claim
```

Using the following `PersistentVolume` and `PersistentVolumeClaim`:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: staging-grafana
  labels:
    failure-domain.beta.kubernetes.io/region: us-east-1
    failure-domain.beta.kubernetes.io/zone: us-east-1b
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-xxxxxxxx
    fsType: ext4
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staging-grafana-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```

And the error I get:

```
12m	12m	1	{default-scheduler }				Normal	Scheduled	Successfully assigned grafana-y0pbq to ip-10-20-10-210.ec2.internal
10m	1m	5	{kubelet ip-10-20-10-210.ec2.internal}		Warning	FailedMount	Unable to mount volumes for pod "grafana-y0pbq_default(a4fd807c-4f1b-11e6-a2d7-12fe6d946c59)": timeout expired waiting for volumes to attach/mount for pod "grafana-y0pbq"/"default". list of unattached/unmounted volumes=[data]
10m	1m	5	{kubelet ip-10-20-10-210.ec2.internal}		Warning	FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "grafana-y0pbq"/"default". list of unattached/unmounted volumes=[data]
```

How can I debug this further?
