### ISSUE TITLE
kube-aws: Node pools

### ISSUE THREAD

**Issue by mumoshu** [coreos/coreos-kubernetes#667]
I'd like to add GKE's "Node Pools" like feature on top of kube-aws so that, without maintaining multiple etcd clusters and kubernetes controller planes, mainly for cost optimization purpose:

(1) I can differentiate
- instance type
- storage size
- instance profile
- security group
- or vice versa..

for each node pool

(2) Make a node pool a spot fleet

Do you think it would be appropriate to implement it in `kube-aws` or in another repo?

cc @colhom

**Comment by colhom** [comment]
@mumoshu to clarify- are you talking about having multiple specifications for worker nodes?

```yaml
workers:
  - instanceType: m3.medium
    count: 4
    labels:
       ....
  - instanceType: t2.small
    count: 20
    labels:
       ....
```

**Comment by mumoshu** [comment]
@colhom Yes. It would also be good to have `availability_zones` configurable per pool like

```
workers:
  - instanceType: m3.medium
    count: 4
    labels:
      ...
    subnets:
    - availabilityZone: ap-northeast-1a
       instanceCIDR: "10.0.0.0/24"
  - instanceType: m3.medium
    count: 4
    labels:
      ...
    subnets:
    - availabilityZone: ap-northeast-1b
       instanceCIDR: "10.0.1.0/24"
```

so that we can also provide a way to solve #668
