### ISSUE TITLE
pod hostPort does not work

### ISSUE THREAD

**Issue by Thermus** [coreos/coreos-kubernetes#674]
Hello,

I have a DS that specifies that a pod with traefik should be started on each node, but the controller node.  However, the hostPort doesn't work. Accessing the port results in the protection being refused. There are no iptables rules in `iptables-save` that indicate that there's a DNAT set up for the local port, not are there any processes listed in `ss -tpnl` that could proxy the traffic. I use kubernetes v1.3.4+coreos.0 on AWS. 

The DS configuration is the following:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-lb
  labels:
    app: traefik-ingress-lb
spec:
  selector:
      matchLabels:
        app: traefik-ingress-lb
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "nodeAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                  {
                    "matchExpressions": [
                      {
                        "key": "controller",
                        "operator": "DoesNotExist"
                      }
                    ]
                  }
                ]
              }
            }
          }
          
      labels:
        app: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: containous/traefik:v1.0.2
          name: traefik-ingress-lb
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
            - containerPort: 443
              hostPort: 443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
              httpGet:
                  path: /health
                  port: 8080
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
          args:
            - --web
            - --kubernetes
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
```

ps aux:
```
root     26000  2.3  0.5  27544 20296 ?        Ssl  10:52   1:13 /traefik --web --kubernetes
```
docker ps:
```
CONTAINER ID        IMAGE                                                                                                   COMMAND                  CREATED             STATUS              P
ORTS               NAMES
264f4fc138ed        containous/traefik:v1.0.2                                                                               "/traefik --web --kub"   53 minutes ago      Up 53 minutes                           k8s_traefik-ingress-lb.d2560973_traefik-ingress-lb-ei9qv_default_a0fa4392-7bfb-11e6-b376-0253cca96ab9_96e4af4a
e87f3f9ed6c5        gcr.io/google_containers/pause-amd64:3.0                                                                "/pause"                 53 minutes ago      Up 53 minutes                           k8s_POD.d8dbe16c_traefik-ingress-lb-ei9qv_default_a0fa4392-7bfb-11e6-b376-0253cca96ab9_541e8aca
```
