### ISSUE TITLE
after upgrade kubelet to 1.4.0, all pods in a worker node has a network issue

### ISSUE THREAD

**Issue by rdtr** [coreos/coreos-kubernetes#702]
Hi,

I installed k8s on AWS CoreOS cluster by following this step by step guide.
https://coreos.com/kubernetes/docs/latest/getting-started.html
This is a really nice article so that without this, I might have gave up using k8s. Thank you.

Now you provide us the k8s v1.4 image for CoreOS, so I'm updating my cluster using kubelet version `v1.4.0_coreos.1`.
This time I noticed the network configuration has been also changed since I last installed (1.3.2), so just updating the kubelet version is not sufficient. I carefully checked diffs and apply them manually then it looked master components are successfully updated.

But when I'm upgrading worker nodes, I noticed pods on the worker upgraded crashes. k8s dashboard also happened to be on the node and the log is:
```
% kubectl logs -f kubernetes-dashboard-v1.4.0-jku1h -n=kube-system
Starting HTTP server on port 9090
Creating API server client for https://10.11.0.1:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.11.0.1:443/version: dial tcp 10.11.0.1:443: getsockopt: no route to host
```

Other pods also failed to communicate with external DB endpoint. nslookup doesn't work on the pod on the node as well.

My files are:
`/etc/systemd/system/kubelet.service`
```
[Service]
Environment=KUBELET_VERSION=v1.4.0_coreos.1
Environment=KUBELET_ACI=quay.io/coreos/hyperkube
Environment="RKT_OPTS=--volume dns,kind=host,source=/etc/resolv.conf \
  --mount volume=dns,target=/etc/resolv.conf \
  --volume rkt,kind=host,source=/opt/bin/host-rkt \
  --mount volume=rkt,target=/usr/bin/rkt \
  --volume var-lib-rkt,kind=host,source=/var/lib/rkt \
  --mount volume=var-lib-rkt,target=/var/lib/rkt \
  --volume stage,kind=host,source=/tmp \
  --mount volume=stage,target=/tmp \
  --volume var-log,kind=host,source=/var/log \
  --mount volume=var-log,target=/var/log"
ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
ExecStartPre=/usr/bin/mkdir -p /var/log/containers
ExecStart=/usr/lib/coreos/kubelet-wrapper   --api-servers=https://[load balancer domain]   --cni-conf-dir=/etc/kubernetes/cni/net.d   --network-plugin=cni   --container-runtime=docker   --rkt-path=/usr/bin/rkt   --rkt-stage1-image=coreos.com/rkt/stage1-coreos   --register-node=true   --allow-privileged=true   --config=/etc/kubernetes/manifests   --hostname-override=[host ip address]   --cluster_dns=10.11.0.10   --cluster_domain=cluster.local   --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml   --tls-cert-file=/etc/kubernetes/ssl/worker.pem   --tls-private-key-file=/etc/kubernetes/ssl/worker-key.pem
Restart=always
RestartSec=10
```

`/opt/bin/host-rkt`
```
#!/bin/sh
exec nsenter -m -u -i -n -p -t 1 -- /usr/bin/rkt "$@"
```

`/etc/kubernetes/worker-kubeconfig.yaml`
```
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    certificate-authority: /etc/kubernetes/ssl/ca.pem
users:
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/ssl/worker.pem
    client-key: /etc/kubernetes/ssl/worker-key.pem
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
```

`/etc/kubernetes/manifests/kube-proxy.yaml`
```
apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
  annotations:
    rkt.alpha.kubernetes.io/stage1-name-override: coreos.com/rkt/stage1-fly
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: quay.io/coreos/hyperkube:v1.4.0_coreos.1
    command:
    - /hyperkube
    - proxy
    - --master=https://[load balancer domain]
    - --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: "ssl-certs"
    - mountPath: /etc/kubernetes/worker-kubeconfig.yaml
      name: "kubeconfig"
      readOnly: true
    - mountPath: /etc/kubernetes/ssl
      name: "etc-kube-ssl"
      readOnly: true
    - mountPath: /var/run/dbus
      name: dbus
      readOnly: false
  volumes:
  - name: "ssl-certs"
    hostPath:
      path: "/usr/share/ca-certificates"
  - name: "kubeconfig"
    hostPath:
      path: "/etc/kubernetes/worker-kubeconfig.yaml"
  - name: "etc-kube-ssl"
    hostPath:
      path: "/etc/kubernetes/ssl"
  - hostPath:
      path: /var/run/dbus
    name: dbus
```

`/etc/systemd/system/flanneld.service.d/40-ExecStartPre-symlink.conf.conf`
```
[Service]
ExecStartPre=/usr/bin/ln -sf /etc/flannel/options.env /run/flannel/options.env
```

`/etc/systemd/system/docker.service.d/40-flannel.conf`
```
[Unit]
Requires=flanneld.service
After=flanneld.service
[Service]
EnvironmentFile=/etc/kubernetes/cni/docker_opts_cni.env
```

`/etc/kubernetes/cni/net.d/10-flannel.conf`
```
{
    "name": "podnet",
    "type": "flannel",
    "delegate": {
        "isDefaultGateway": true
    }
}
```

`/etc/flannel/options.env`
```
FLANNELD_IFACE=[host ip]
FLANNELD_ETCD_ENDPOINTS=[etcd ip],...
```

Then I ran
`sudo systemctl daemon-restart`
`sudo systemctl kubelet`
`sudo systemctl flanneld`
`sudo systemctl docker`

and about add-ons, I manually updated to the latest version by using yaml files in this repository.

Currently I'm stuck in the middle of a step of upgrading and don't know what is the root issue of this. Restarting a node didn't work. If I move a pod to other nodes, it just works.
Am I missing something? I suspect a change of network configuration going something wrong, but couldn't figure out how to fix it.
I'd appreciate if someone have an idea what causes this issue.

[other info]
I use flannel but don't use Calico.
A log of kube proxy:
```
E1001 06:04:59.245168       1 server.go:369] Can't get Node "ip-xxx.ec2.internal", assuming iptables proxy, err: nodes "ip-xxx.ec2.internal" not found
I1001 06:04:59.249956       1 server.go:203] Using iptables Proxier.
W1001 06:04:59.262380       1 server.go:417] Failed to retrieve node info: nodes "ip-xxx-6.ec2.internal" not found
W1001 06:04:59.265461       1 proxier.go:226] invalid nodeIP, initialize kube-proxy with 127.0.0.1 as nodeIP
I1001 06:04:59.265514       1 server.go:215] Tearing down userspace rules.
I1001 06:04:59.281138       1 conntrack.go:40] Setting nf_conntrack_max to 65536
I1001 06:04:59.281765       1 conntrack.go:57] Setting conntrack hashsize to 16384
I1001 06:04:59.281939       1 conntrack.go:62] Setting nf_conntrack_tcp_timeout_established to 86400
```
