### ISSUE TITLE
Hang with df -h

### ISSUE THREAD

**Issue by keimoon** [coreos/coreos-kubernetes#739]
kube-aws version: v0.8.3

CoreOS version:

```
NAME=CoreOS
ID=coreos
VERSION=1122.3.0
VERSION_ID=1122.3.0
BUILD_ID=2016-10-20-2045
PRETTY_NAME="CoreOS 1122.3.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

Kubernetes version: `version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3+coreos.0", GitCommit:"7819c84f25e8c661321ee80d6b9fa5f4ff06676f", GitTreeState:"clean", BuildDate:"2016-10-17T21:19:17Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}`

Kubernetes Controller Instance type: `t2.small`
Kubernetes Worker Instance type: `m4.xlarge`

We ran into an issue where commands like `df -h` hang on `worker server`. We ran with `strace` and it hang at:

```
stat("/proc/sys/fs/binfmt_misc",
```

Rebooting worker instances will resolve the problem temporarily, but after about 1 day it will occur again.

**Comment by pbx0** [comment]
@keimoon Is `df -h` being run inside a pod/container or is it directly executed on the host? If it is a pod could you share the pod manifest?

**Comment by felixbuenemann** [comment]
@keimoon I had a workaround for this on CoreOS stable which consisted of the following drop-in:

```yaml
coreos:
  units:
    - name: docker.service
      drop-ins:
        - name: 60-mount-binfmt-misc.conf
          content: |
            [Unit]
            Wants=proc-sys-fs-binfmt_misc.mount
            After=proc-sys-fs-binfmt_misc.mount
```

My git commit message for that change said:

> Add workaround for binfmt_misc automount issues
>
> Without this fix storage monitoring in telegraf is not working because
the try to trigger the automount of /rootfs/proc/sys/fs/binfmt_misc
fails and causes a "Too many levels of symbolic links" error.

This fix is no longer working for me on CoreOS beta, so maybe I need to revert it because the underlying systemd issue was fixed.
