### ISSUE TITLE
kube-aws: Scheduled Jobs not running

### ISSUE THREAD

**Issue by danielfm** [coreos/coreos-kubernetes#742]
I created a test cluster with kube-aws v0.8.3 with no changes to the generated templates and tried to follow the [Scheduled Job](http://kubernetes.io/docs/user-guide/scheduled-jobs/) documentation page.

At first, I wasn't able to create the ScheduledJob object via the API server so, as instructed by the documentation, I enabled the `batch/v2alpha1` group in the API server via the `--runtime-config` option:

``` yaml
#cloud-config
coreos:

  # ...
  - path: /etc/kubernetes/manifests/kube-apiserver.yaml
    content: |
      # ...
          command:
          - /hyperkube
          - apiserver
          # ...
          - --runtime-config=extensions/v1beta1/networkpolicies=true,batch/v2alpha1=true
          # ...
```

This allowed me to create the Scheduled Job:

```
$ kubectl create -f ~/sample-job.yaml
scheduledjob "hello" created
```

This is the content of `~/sample-job.yaml` (identical to the Kubernetes docs):

``` yaml
apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  name: hello
spec:
  schedule: 0/1 * * * ?
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

The problem is that no jobs get scheduled at all. The expected behavior is the creation of one Job per minute.

I tested the same manifest against minikube v0.12.0, and it works as expected, so I figured it might be an issue with kube-aws.

[This issue](https://github.com/kubernetes/kubernetes/issues/35508) might be related, so let me just link them both here.
