### ISSUE TITLE
Create persistent volume claim failed on coreos+k8s+ceph.

### ISSUE THREAD

**Issue by sysit** [coreos/coreos-kubernetes#743]
CoreOS version is stable (1122.2) .
Hyperkube version is v1.4.3_coreos.0
ceph version is jewel

use generic scripts of this project installed k8s multi-node cluster.  and modified kubelet.service by [this document](https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/kubelet-wrapper.md) recommand  for ceph rbd.

and refer the  kubernetes[ example file](https://github.com/kubernetes/kubernetes/tree/master/examples/experimental/persistent-volume-provisioning), created ceph-secret/storageclass resource.  the yaml:

 **ceph-secret-admin.yaml** 

```
    apiVersion: v1
    kind: Secret
    metadata:
      name: ceph-secret-admin
      namespace: kube-system
    data:
      key: QVFDTEl2NVg5c0U2R1JBQVRYVVVRdUZncDRCV294WUJtME1hcFE9PQ==
```

 **ceph-secret-user.yaml** 

```
    apiVersion: v1
    kind: Secret
    metadata:
      name: ceph-secret-user
    data:
      key: QVFDTEl2NVg5c0U2R1JBQVRYVVVRdUZncDRCV294WUJtME1hcFE9PQ==
```

 **rbd-storage-class.yaml**

```
    apiVersion: storage.k8s.io/v1beta1
    kind: StorageClass
    metadata:
      name: kubepool
      annotations:
        storageclass.beta.kubernetes.io/is-default-class: 'true'
    provisioner: kubernetes.io/rbd
    parameters:
        monitors: 10.199.134.2:6789,10.199.134.3:6789,10.199.134.4:6789
        adminId: rbd
        adminSecretName: ceph-secret-admin
        adminSecretNamespace: kube-system
        pool: rbd
        userId: rbd
        userSecretName: ceph-secret-user
```

   **claim1.json :**

```
     {
      "kind": "PersistentVolumeClaim",
      "apiVersion": "v1",
      "metadata": {
        "name": "claim1",
        "annotations": {
            "volume.beta.kubernetes.io/storage-class": "kubepool"
        }
      },
      "spec": {
        "accessModes": [
          "ReadWriteOnce"
        ],
        "resources": {
          "requests": {
            "storage": "3Gi"
          }
        }
      }
    }
```

when I  create pvc,  it's alway show pending status , describe show message:

```
Name:           claim1
Namespace:      default
Status:         Pending
Volume:
Labels:         <none>
Capacity:
Access Modes:
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  16m           14s             66      {persistentvolume-controller }                  Warning         ProvisioningFailed      no volume plugin matched
```

what's wrong with me ?

btw: I can mount ceph rbd device into coreos host.
