### ISSUE TITLE
libvirt kube-up.sh nodes never ready

### ISSUE THREAD

**Issue by muteor** [coreos/coreos-kubernetes#811]
I am following the libvirt-coreos guide here: https://kubernetes.io/docs/getting-started-guides/libvirt-coreos/

When I use `kube-up.sh` nodes never become ready, however the vms are started and the master is running.

Here is the output from `kube-up.sh`

```
root@bumblebee:/data/kubernetes# rm ~/.kube/config
root@bumblebee:/data/kubernetes# ./cluster/kube-up.sh
... Starting cluster using provider: libvirt-coreos
... calling verify-prereqs
... calling kube-up
KUBE_MASTER_IP: 192.168.10.1
KUBE_MASTER: kubernetes-master
--2017-01-14 09:19:19--  https://alpha.release.core-os.net/amd64-usr/current/coreos_production_qemu_image.img.bz2
Resolving alpha.release.core-os.net (alpha.release.core-os.net)... 104.16.20.26, 104.16.21.26
Connecting to alpha.release.core-os.net (alpha.release.core-os.net)|104.16.20.26|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘./cluster/../cluster/../cluster/libvirt-coreos/coreos_production_qemu_image.img.bz2’ not modified on server. Omitting download.

Pool kubernetes refreshed

TLS assets generated...
Network kubernetes_global created from ./cluster/../cluster/../cluster/libvirt-coreos/network_kubernetes_global.xml

Network kubernetes_pods created from ./cluster/../cluster/../cluster/libvirt-coreos/network_kubernetes_pods.xml

Vol kubernetes-node-1.img created

Pool kubernetes refreshed

Domain kubernetes-node-1 created from /tmp/tmp.hYxpMaK013

Vol kubernetes-node-2.img created

Pool kubernetes refreshed

Domain kubernetes-node-2 created from /tmp/tmp.SygUlVLVmF

Vol kubernetes-node-3.img created

Pool kubernetes refreshed

Domain kubernetes-node-3 created from /tmp/tmp.CEMKYOPRt4

Vol kubernetes-master.img created

Pool kubernetes refreshed

Domain kubernetes-master created from /tmp/tmp.feuy17i3Rq

Cluster "libvirt-coreos" set.
User "libvirt-coreos" set.
Context "libvirt-coreos" set.
Switched to context "libvirt-coreos".
Wrote config for libvirt-coreos to /root/.kube/config
Wait for cluster readiness
Nb ready nodes: 0 / 3
.......
```

```
root@bumblebee:/data/kubernetes# virsh -c qemu:///system list
 Id    Name                           State
----------------------------------------------------
 25    kubernetes-node-1              running
 26    kubernetes-node-2              running
 27    kubernetes-node-3              running
 28    kubernetes-master              running
```

Master node:

```
root@bumblebee:/data/kubernetes# ssh core@192.168.10.1
Last login: Sat Jan 14 09:22:52 UTC 2017 from 192.168.10.254 on pts/0
Container Linux by CoreOS alpha (1284.2.0)

core@kubernetes-master ~ $ journalctl -u kubelet
-- No entries --

core@kubernetes-master ~ $ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1284.2.0
VERSION_ID=1284.2.0
BUILD_ID=2017-01-10-0545
PRETTY_NAME="Container Linux by CoreOS 1284.2.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

core@kubernetes-master ~ $ systemctl list-unit-files | grep kube
opt-kubernetes.mount                   static
kube-addons.service                    disabled
kube-apiserver.service                 disabled
kube-controller-manager.service        disabled
kube-scheduler.service                 disabled
```

Config:

```
root@bumblebee:/data/kubernetes# cat ~/.kube/config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: http://192.168.10.1:8080
  name: libvirt-coreos
contexts:
- context:
    cluster: libvirt-coreos
    user: libvirt-coreos
  name: libvirt-coreos
current-context: libvirt-coreos
kind: Config
preferences: {}
users:
- name: libvirt-coreos
  user:
    client-certificate-data: ...
    client-key-data: ...
```

I don't think I am missing anything obvious, any help would be appreciated.

Thanks
