### ISSUE TITLE
CephFS: mount failed: mount failed: exit status 32

### ISSUE THREAD

**Issue by Promaethius** [coreos/coreos-kubernetes#838]
```
MountVolume.SetUp failed for volume "kubernetes.io/cephfs/f0b62db6-f560-11e6-adac-0cc47ab587f4-cephfs" (spec.Name: "cephfs") pod "f0b62db6-f560-11e6-adac-0cc47ab587f4" (UID: "f0b62db6-f560-11e6-adac-0cc47ab587f4") with: CephFS: mount failed: mount failed: exit status 32 Mounting command: mount Mounting arguments: ceph-mon.ceph:6789:/ /var/lib/kubelet/pods/f0b62db6-f560-11e6-adac-0cc47ab587f4/volumes/kubernetes.io~cephfs/cephfs ceph [name=admin,secret=AQCRWqdYAAAAABAANTwImUBBwKl3sK1ym7MjCw== ] Output: mount: mount ceph-mon.ceph:6789:/ on /var/lib/kubelet/pods/f0b62db6-f560-11e6-adac-0cc47ab587f4/volumes/kubernetes.io~cephfs/cephfs failed: No such process
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: cephfs
  name: ceph-cephfs-test
  namespace: ceph
spec:
  nodeSelector:
    node-type: storage
  containers:
  - name: cephfs-rw
    image: busybox
    command:
    - sh
    - -c
    - while true; do sleep 1; done
    volumeMounts:
    - mountPath: "/mnt/cephfs"
      name: cephfs
  volumes:
  - name: cephfs
    cephfs:
      monitors:
#This only works if you have skyDNS resolveable from the kubernetes node. Otherwise you must manually put in one or more mon pod ips.
      - ceph-mon.ceph:6789
      user: admin
      secretRef:
        name: ceph-client-key
```

Would it be possible to add the cephfs binaries to hyperkube?
